### PR TITLE
Added Forms category and added TellForm

### PR DESCRIPTION
**Pull request by whitef0x0**

### CODE REVIEW

**Comment by vdeturckheim** [comment]
@whitef0x0 Thanks for contributing. I will review it!

**Comment by vdeturckheim** [comment]
@whitef0x0 I'm having a hard time starting the project. After login, I get 401 errors, so my browser goes to login, but I'm logged -> infinte loop...

Am I doing anything wrong ?

**Comment by whitef0x0** [comment]
@vdeturckheim you need to set the correct domain. The reason why it is redirecting you is because the cookie domain isn't the same as your url so it redirects. To set it up you need to use dnsmasq or equivalent to map subdomains to localhost.

**Comment by vdeturckheim** [comment]
@whitef0x0 trying that. Thanks !

**Comment by vdeturckheim** [comment]
Great project, thanks @whitef0x0 .

**Comment by whitef0x0** [comment]
@vdeturckheim if you need help you can always reach me at polydaic at gmail or try our gitter channel (gitter.im/tellform)

**Pull request merged**
