### PR TITLE
Added sharelatex

### PR DESCRIPTION
**Pull request by henryoswald**

### CODE REVIEW

**Comment by vdeturckheim** [comment]
@henryoswald thanks for contributing. I will try to run the project :)

**Comment by vdeturckheim** [comment]
@henryoswald I followed the instructions [here](https://github.com/sharelatex/sharelatex/wiki/Setting-up-a-Development-Environment) but could not manage to run the project locally. Is there any gotcha you are aware of ?
Also, I'm not very comfortable with a project which .nvmrc contains `0.10.26`.

**Comment by henryoswald** [comment]
some of our >15 processes are still on node 0.10. We recommend using docker when you want to install ShareLaTeX to make life simple. To get to hello world working try just cloning the web project https://github.com/sharelatex/web-sharelatex and doing a npm install && grunt with redis and mongo running.

**Comment by vdeturckheim** [comment]
Thanks for the clarifications, I will take another look.

**Pull request closed without merging**
