### PR TITLE
Added Monitaure

### PR DESCRIPTION
**Pull request by Bertrand31**

### CODE REVIEW

**Comment by vdeturckheim** [comment]
@Bertrand31 Thanks for contributing! I'll look at that!

**Comment by vdeturckheim** [comment]
@Bertrand31 I have a hard time testing it; I did:
* `npm install`
* `npm run start:dev`

goto localhost:1337. I end up with an empty page with the error in the console:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by Bertrand31** [comment]
Do you have any ouput in your terminal?

**Comment by vdeturckheim** [comment]
last logs (even after requests) where:
```
debug: -------------------------------------------------------
debug: :: Mon Nov 07 2016 10:31:05 GMT+0100 (CET)

debug: Environment : development
debug: Port        : 1337
debug: -------------------------------------------------------
```

**Comment by Bertrand31** [comment]
Have you ran `npm run webpack:dev` in another console?
Also, try opening `http://127.0.0.1:1337/`.

**Comment by vdeturckheim** [comment]
Yes, it does not change much here. I'll try on another machine on Friday.

**Pull request closed without merging**
