### PR TITLE
Add nscm to Developers section

### PR DESCRIPTION
**Pull request by bnb**
Adds the `nscm` open source tool to the Developers section of the list ❤️

### CODE REVIEW

**Comment by vdeturckheim** [comment]
Thanks @bnb , I'll review it soon ;)

**Comment by vdeturckheim** [comment]
@bnb do I have to change my npm config to test it?

**Comment by bnb** [comment]
@vdeturckheim Just checked, and you do have to have your npm registry set to a Certified Modules registry. So, I suppose there's a distinction - tool itself is open-source, but to use it you need to have your registry configured with Certified Modules. Not sure if that's a deal-breaker 🤔

**Comment by vdeturckheim** [comment]
@bnb it should be good, just that it might take 5 minutes to test and not 2 :p I'll do it when I have a few minutes :)

**Pull request merged**
