### PR TITLE
add hilary

### PR DESCRIPTION
**Pull request by vdeturckheim**

### CODE REVIEW

**Comment by vdeturckheim** [comment]
Uninstallable -> weird dependencies.

**Comment by sallakarppinen** [comment]
Hello, I'm one of the contributors to OAE. Could you clarify which dependencies were giving you trouble so we can improve documentation?

**Comment by vdeturckheim** [comment]
Hey @sallakarppinen thanks for helping here!
I did not manage to start the project locally on Ubuntu. I might be too quick to blame the lot of dependencies (Cassandra, RabbitMq, Etherpad, ...). Would you consider havin a docker-compose setting up the external dependencies for the project ?

**Comment by sallakarppinen** [comment]
Hmm, I don't have much (read: none) experience with docker so I've asked another contributor @davidoae for input on that, but I do have Hilary running locally on Ubuntu set up using the instructions in README.md... It's pretty strict about the versions of some dependencies (specifically Cassandra and Etherpad), but does work. You can also try out the production version [here](https://network.unity.ac/).

**Comment by vdeturckheim** [comment]
Oh, ok, I used the latest versions of several of the deps... probably where I failed ^^
I'm pretty impressed with the production version ;)
On this list I try to run most of the projects locally myself, partly to test Sqreen on them, but also to ensure anyone can step-in and contribute to the listed projects.

**Comment by sallakarppinen** [comment]
Yeah, there's been a lot of talk about updating the deps but unfortunately we're a bit low on contributors and reviewers at the moment... I know it's a bit of a pain to set up! I hope we'll be able to simplify that in the future. There are [Vagrant instructions](https://github.com/oaeproject/puppet-hilary) as well although I haven't personally tried those.

**Comment by vdeturckheim** [comment]
I'll keep Hilary on the backlog for now (I'll be back to it next week or later in November) :) Let me know if there is any updates.

**Comment by sallakarppinen** [comment]
Hullo, I know this was quite a while ago but we are now trialling a docker-compose set up for OAE Project and I wondered if maybe you wanted to have a look? It's still in testing, but the instructions are [here](https://github.com/oaeproject/Hilary/wiki/Call-for-feedback-on-docker-install-and-setup-instructions).

**Pull request closed without merging**
