### PR TITLE
Add Strapi

### PR DESCRIPTION
**Pull request by pierreburgy**

### CODE REVIEW

**Comment by vdeturckheim** [comment]
@pierreburgy  thanks for contributing! I will review it.

**Comment by vdeturckheim** [comment]
@pierreburgy My understanding is that Strapi is a framework. This repo aims at listing full applications written in Node.js. Maybe https://github.com/sindresorhus/awesome-nodejs would be a better fit here :).

Let me know if I am mistaken here!

**Comment by pierreburgy** [comment]
@vdeturckheim: actually, Strapi is more a CMS than a framework: it includes an admin panel, user authentication, email API, upload API... It can be compared to Keystone.

**Comment by vdeturckheim** [comment]
@pierreburgy oh, my bad then, I may have read the doc too quickly ;) I will review it then. Thanks for the clarification.

**Comment by pierreburgy** [comment]
No worries. Thanks a lot!

**Pull request merged**
