### PR TITLE
Add Loopback

### PR DESCRIPTION
**Pull request by atherdon**

### CODE REVIEW

**Comment by vdeturckheim** [comment]
Hey, thanks for contributing. Loopback is more a framework than an app made with node really. More a candidate for https://github.com/sindresorhus/awesome-nodejs ;)

**Comment by atherdon** [comment]
@vdeturckheim But it's awesome... :(
Maybe I can change PR and add another section, related to frameworks?

**Comment by vdeturckheim** [comment]
Having frameworks does not really fills the goal of this repo which is to show real projects built with nodejs, not tools used to build projects. (see the story here https://medium.com/@vdeturckheim/the-story-of-how-i-got-first-place-on-hacker-news-and-got-1000-stars-on-github-9dc9e63ef829 ).

**Comment by atherdon** [comment]
Ok, I can only one option - I agree with you.

**Pull request closed without merging**
