### PR TITLE
Added Cerebro to Electron apps section

### PR DESCRIPTION
**Pull request by KELiON**
Cerebro is an open-source electron-based application like Alfred or Spotligh

### CODE REVIEW

**Comment by vdeturckheim** [comment]
@KELiON thanks for contributing. I will review it!

**Comment by vdeturckheim** [comment]
It did not work after following the dev instructions on ubuntu :/

**Comment by KELiON** [comment]
@vdeturckheim can you clarify what exactly did not work?

**Comment by vdeturckheim** [comment]
after `yarn run dev`, I got:

```
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from undefined
    at TypeError (native)
    at exports.default (/home/vladimir/tmp/cerebro/app/main/createWindow.js:48:18)
    at App._electron.app.on (/home/vladimir/tmp/cerebro/app/main.development.js:36:16)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
```

then

```
Uncaught Exception:
TypeError: Cannot read property 'webContents' of undefined
    at EventEmitter._electron.ipcMain.on (/home/vladimir/tmp/cerebro/app/main.development.js:64:37)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/home/vladimir/tmp/cerebro/node_modules/electron-prebuilt/dist/resources/electron.asar/browser/api/web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```
```
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from undefined
    at TypeError (native)
    at exports.default (/home/vladimir/tmp/cerebro/app/main/createWindow.js:48:18)
    at App._electron.app.on (/home/vladimir/tmp/cerebro/app/main.development.js:36:16)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
```
After that, the app seemed to work properly, do you have any idea why thoses stacktaces ?

**Comment by KELiON** [comment]
@vdeturckheim looks weird! No one had this kind of issue before. What OS do you use?

**Comment by vdeturckheim** [comment]
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

**Pull request closed without merging**
